main: me.emnichtdayt.voicechat.VoiceChatMain
name: VoiceChat
api-version: 1.14
version: 1.0
description: VoiceChat
author: EmnichtdaYT
website: emnichtdayt.lima-city.de

depend: [WorldGuard]
loadbefore: [WorldGuard]

commands:
    voicechatinfo:
         description: info